version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/project-1"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/project-2"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
